In [26]:
import numpy as np

In [27]:
import array

In [3]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [4]:
type(np.array([1,2,3,4]))

numpy.ndarray

In [5]:
np.array([1,2.0,3,4,4.6,6.8])

array([1. , 2. , 3. , 4. , 4.6, 6.8])

In [6]:
np.array([1,2,3,4,"shivang",4+8j])

array(['1', '2', '3', '4', 'shivang', '(4+8j)'], dtype='<U64')

In [7]:
#2d array
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [32]:
np.array([(1,2),(3,4)])

array([[1, 2],
       [3, 4]])

In [10]:
#3d array
np.array([[[1,2],[2,3]],[[3,4],[4,5]],[[6,7],[7,8]]])

array([[[1, 2],
        [2, 3]],

       [[3, 4],
        [4, 5]],

       [[6, 7],
        [7, 8]]])

In [12]:
np.array([[1,2],[2,3],[4,5,6]])

C:\Users\shiva\AppData\Local\Temp/ipykernel_10568/2670448388.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[1,2],[2,3],[4,5,6]])


array([list([1, 2]), list([2, 3]), list([4, 5, 6])], dtype=object)

In [13]:
np.array([1,2,3], ndmin=3)

array([[[1, 2, 3]]])

In [14]:
np.array([1,2,3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [34]:
#here the value of a is [1,2] and the value of b is [4,5]
arr= np.array([[1,2],[4,5]], dtype= [("a","<i4"), ("b","<i8")])
arr

array([[(1, 1), (2, 2)],
       [(4, 4), (5, 5)]], dtype=[('a', '<i4'), ('b', '<i8')])

In [39]:
arr[0][1]

(2, 2)

In [35]:
#here the value of a is 1 and 4 & value of b is 2 and 5
arr1 = np.array([(1,2) , (4,5)],dtype = [("a",'<i4'), ("b",'<i8')])
arr1

array([(1, 2), (4, 5)], dtype=[('a', '<i4'), ('b', '<i8')])

In [40]:
arr1[0][0]

2

In [42]:
type(arr1[0][0])

numpy.int32

In [41]:
arr1[1][1]

5

In [43]:
type(arr1[1][1])

numpy.int64

In [45]:
ar= np.array([[1,2],[3,4]])

In [48]:
ar[0]

array([1, 2])

In [47]:
type(ar[0])

numpy.ndarray

In [49]:
ar[0][1]

2

In [50]:
type(ar[0][1])

numpy.int32

In [51]:
#matrix
np.mat(ar)

matrix([[1, 2],
        [3, 4]])

In [52]:
np.matrix(ar)

matrix([[1, 2],
        [3, 4]])

In [53]:
l= [1,2,3,4,5,6,7]

In [54]:
np.array(l)

array([1, 2, 3, 4, 5, 6, 7])

In [55]:
np.asarray(l)

array([1, 2, 3, 4, 5, 6, 7])

In [56]:
np.asanyarray(l)

array([1, 2, 3, 4, 5, 6, 7])

In [57]:
matr= np.mat(ar)

In [58]:
matr

matrix([[1, 2],
        [3, 4]])

In [59]:
# matrix will not be converted into array by using asanyarray function because matrix is itself an array and matrix is the 
# subset (child class) of the array as well. If the dataset is in any form of array then asanyarray fn will not convert that
#to array. So here matrix can't be converted into array whereas list will be converted into array using asanyarray function.

np.asanyarray(matr)

matrix([[1, 2],
        [3, 4]])

In [60]:
# asarray fn can convert matrix into array.

np.asarray(matr)

array([[1, 2],
       [3, 4]])

In [61]:
# to check whether matrix is a subclass of array or not

issubclass(np.matrix, np.ndarray)

True

In [62]:
issubclass(np.ndarray, np.matrix)

False

In [78]:
ar= np.array([[1,2],[3,4]])
ar

array([[1, 2],
       [3, 4]])

In [79]:
# deep copy and shallow copy

In [80]:
# shallow copy

a= ar

In [81]:
# deep copy

b= np.copy(ar)

In [82]:
ar[0][1]= 67

In [83]:
ar

array([[ 1, 67],
       [ 3,  4]])

In [84]:
a

array([[ 1, 67],
       [ 3,  4]])

In [85]:
b

array([[1, 2],
       [3, 4]])

In [88]:
b[0:10]

array([[1, 2],
       [3, 4]])

In [89]:
ar[-1]

array([3, 4])

In [90]:
for i in ar:
    print (i)

[ 1 67]
[3 4]


In [91]:
np.fromfunction(lambda i,j : i==j, (4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [92]:
type(np.fromfunction(lambda i,j : i==j, (4,4)))

numpy.ndarray

In [93]:
np.fromfunction(lambda i,j : i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [94]:
np.fromfunction(lambda i,j : i**j, (3,3))

array([[1., 0., 0.],
       [1., 1., 1.],
       [1., 2., 4.]])

In [95]:
np.fromfunction(lambda i,j : i/j, (3,3))

C:\Users\shiva\AppData\Local\Temp/ipykernel_10568/506192477.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.fromfunction(lambda i,j : i/j, (3,3))
C:\Users\shiva\AppData\Local\Temp/ipykernel_10568/506192477.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.fromfunction(lambda i,j : i/j, (3,3))


array([[nan, 0. , 0. ],
       [inf, 1. , 0.5],
       [inf, 2. , 1. ]])

In [1]:
0/0

ZeroDivisionError: division by zero

In [2]:
1/0

ZeroDivisionError: division by zero

In [7]:
## list comprehension
x= [i*i for i in range(5)]
x

[0, 1, 4, 9, 16]

In [30]:
## generator object
gen = (i*i for i in range(5))
gen

<generator object <genexpr> at 0x0000028B5A6AD890>

In [23]:
next(gen)

1

In [24]:
for i in gen:
    print (i)

4
9
16


In [19]:
def test(x):
    yield x

x= test(5)
next(x)

5

In [28]:
np.fromiter(range(5),dtype=int)

array([0, 1, 2, 3, 4])

In [31]:
np.fromiter(gen, dtype=int)

array([ 0,  1,  4,  9, 16])

In [32]:
np.fromstring('1,2,3,4,5', sep=",", dtype= int)

array([1, 2, 3, 4, 5])

In [33]:
np.fromstring("20 30 40 50 60", sep=" ", dtype= complex)

array([20.+0.j, 30.+0.j, 40.+0.j, 50.+0.j, 60.+0.j])

In [34]:
## 1d array
l= [1,2,3,4,5]

In [36]:
arr= np.array(l)

In [41]:
type(arr)

numpy.ndarray

In [48]:
arr.ndim

1

In [49]:
arr.size

5

In [50]:
arr.shape

(5,)

In [51]:
arr.dtype

dtype('int32')

In [39]:
## 2d array
arr1= np.array([[1,2,3,4], [3,4,5,6], [7,8,9,10]])

In [40]:
arr1

array([[ 1,  2,  3,  4],
       [ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])

In [42]:
type(arr1)

numpy.ndarray

In [43]:
arr1.ndim

2

In [44]:
arr1.size

12

In [46]:
arr1.shape

(3, 4)

In [47]:
arr1.dtype

dtype('int32')

In [52]:
arr2= np.array([[[1,2,3,4], [5,6,7,8]], [[9,10,11,12],[13,14,15,16]]])

In [55]:
arr2

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [53]:
type(arr2)

numpy.ndarray

In [54]:
arr2.ndim

3

In [56]:
arr2.shape

(2, 2, 4)

In [57]:
arr2.size

16

In [58]:
arr2.dtype

dtype('int32')

In [59]:
list(range(5))

[0, 1, 2, 3, 4]

In [60]:
list(range(6.6,9,-.3))

TypeError: 'float' object cannot be interpreted as an integer

In [61]:
np.arange(9,6.6,-.3)

array([9. , 8.7, 8.4, 8.1, 7.8, 7.5, 7.2, 6.9, 6.6])

In [62]:
np.arange(1,9)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [64]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [65]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [66]:
np.zeros((2,5,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [67]:
np.ones(4)

array([1., 1., 1., 1.])

In [70]:
np.ones((2,3,1))+5

array([[[6.],
        [6.],
        [6.]],

       [[6.],
        [6.],
        [6.]]])

In [71]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [73]:
np.empty((3,4))

array([[1.38213941e-311, 3.16202013e-322, 0.00000000e+000,
        0.00000000e+000],
       [1.13073288e+277, 2.05573392e+160, 4.27405984e-033,
        5.73632180e+174],
       [3.69779781e-033, 5.39851231e-066, 5.28979036e+174,
        7.17030841e-038]])

In [76]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [96]:
np.linspace([1,6],4,endpoint=False,axis=1)

array([[1.  , 1.06, 1.12, 1.18, 1.24, 1.3 , 1.36, 1.42, 1.48, 1.54, 1.6 ,
        1.66, 1.72, 1.78, 1.84, 1.9 , 1.96, 2.02, 2.08, 2.14, 2.2 , 2.26,
        2.32, 2.38, 2.44, 2.5 , 2.56, 2.62, 2.68, 2.74, 2.8 , 2.86, 2.92,
        2.98, 3.04, 3.1 , 3.16, 3.22, 3.28, 3.34, 3.4 , 3.46, 3.52, 3.58,
        3.64, 3.7 , 3.76, 3.82, 3.88, 3.94],
       [6.  , 5.96, 5.92, 5.88, 5.84, 5.8 , 5.76, 5.72, 5.68, 5.64, 5.6 ,
        5.56, 5.52, 5.48, 5.44, 5.4 , 5.36, 5.32, 5.28, 5.24, 5.2 , 5.16,
        5.12, 5.08, 5.04, 5.  , 4.96, 4.92, 4.88, 4.84, 4.8 , 4.76, 4.72,
        4.68, 4.64, 4.6 , 4.56, 4.52, 4.48, 4.44, 4.4 , 4.36, 4.32, 4.28,
        4.24, 4.2 , 4.16, 4.12, 4.08, 4.04]])

In [89]:
np.logspace([2],[3], axis=0)

array([[ 100.        ],
       [ 104.81131342],
       [ 109.8541142 ],
       [ 115.13953993],
       [ 120.67926406],
       [ 126.48552169],
       [ 132.57113656],
       [ 138.94954944],
       [ 145.63484775],
       [ 152.64179672],
       [ 159.98587196],
       [ 167.68329368],
       [ 175.75106249],
       [ 184.20699693],
       [ 193.06977289],
       [ 202.35896477],
       [ 212.09508879],
       [ 222.29964825],
       [ 232.99518105],
       [ 244.20530945],
       [ 255.95479227],
       [ 268.26957953],
       [ 281.1768698 ],
       [ 294.70517026],
       [ 308.88435965],
       [ 323.74575428],
       [ 339.32217719],
       [ 355.64803062],
       [ 372.75937203],
       [ 390.69399371],
       [ 409.49150624],
       [ 429.19342601],
       [ 449.8432669 ],
       [ 471.48663635],
       [ 494.17133613],
       [ 517.94746792],
       [ 542.86754393],
       [ 568.9866029 ],
       [ 596.36233166],
       [ 625.05519253],
       [ 655.12855686],
       [ 686.648

In [94]:
type(np.logspace([2],[3], axis=1))

numpy.ndarray

In [97]:
d = np.linspace(4,7,40)

In [98]:
d

array([4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
       4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
       4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
       5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846,
       5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
       5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
       6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
       6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ])

In [99]:
d.ndim

1

In [100]:
d.shape

(40,)

In [102]:
d.reshape(40,1)

array([[4.        ],
       [4.07692308],
       [4.15384615],
       [4.23076923],
       [4.30769231],
       [4.38461538],
       [4.46153846],
       [4.53846154],
       [4.61538462],
       [4.69230769],
       [4.76923077],
       [4.84615385],
       [4.92307692],
       [5.        ],
       [5.07692308],
       [5.15384615],
       [5.23076923],
       [5.30769231],
       [5.38461538],
       [5.46153846],
       [5.53846154],
       [5.61538462],
       [5.69230769],
       [5.76923077],
       [5.84615385],
       [5.92307692],
       [6.        ],
       [6.07692308],
       [6.15384615],
       [6.23076923],
       [6.30769231],
       [6.38461538],
       [6.46153846],
       [6.53846154],
       [6.61538462],
       [6.69230769],
       [6.76923077],
       [6.84615385],
       [6.92307692],
       [7.        ]])

In [103]:
d.reshape(2,1,20)

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
         4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
         4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
         5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846]],

       [[5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
         5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
         6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
         6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [104]:
d.reshape(1,4,10)

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
         4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769],
        [4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
         5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846],
        [5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
         5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923],
        [6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
         6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [105]:
d.reshape(1,2,1,20)

array([[[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
          4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
          4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
          5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846]],

        [[5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
          5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
          6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
          6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]]])

In [106]:
d.reshape(3,1,20)

ValueError: cannot reshape array of size 40 into shape (3,1,20)

In [107]:
np.random.rand(3)

array([0.83136817, 0.70638197, 0.04604623])

In [108]:
np.random.randn(5)

array([ 0.38437791, -0.73868572, -0.26859002,  1.62789223, -0.2764209 ])

In [110]:
np.random.randn(2,2,3)

array([[[ 0.22063523,  0.72453458, -0.12878397],
        [ 0.87931917,  1.55024926,  0.14183581]],

       [[ 0.02140556, -2.37775353, -0.60316916],
        [-0.4370867 , -1.62762326, -0.23493267]]])

In [115]:
np.random.randint(4,100, (4,4))

array([[38, 15,  5, 74],
       [57, 27, 10, 36],
       [15, 17, 27, 95],
       [15, 55, 54, 99]])

In [116]:
arr = np.random.randint(3,9, (3,3))

In [117]:
arr

array([[8, 7, 7],
       [3, 6, 7],
       [3, 7, 8]])

In [122]:
arr.reshape(3,1,3)

array([[[8, 7, 7]],

       [[3, 6, 7]],

       [[3, 7, 8]]])

In [124]:
arr.reshape(3,3,1)

array([[[8],
        [7],
        [7]],

       [[3],
        [6],
        [7]],

       [[3],
        [7],
        [8]]])

In [123]:
arr.reshape(1,9)

array([[8, 7, 7, 3, 6, 7, 3, 7, 8]])

In [126]:
arr.reshape(3,-989)

array([[8, 7, 7],
       [3, 6, 7],
       [3, 7, 8]])

In [127]:
arr.reshape(3,-1)

array([[8, 7, 7],
       [3, 6, 7],
       [3, 7, 8]])

In [128]:
arr.reshape(1,-9)

array([[8, 7, 7, 3, 6, 7, 3, 7, 8]])

In [129]:
arr.max()

8

In [130]:
arr.min()

3

In [131]:
arr= np.random.randint(4,100, (5,5))

In [132]:
arr

array([[52, 10, 64, 94, 31],
       [49, 72, 26, 52, 39],
       [58, 52, 71, 94, 14],
       [18, 93, 17, 18, 99],
       [58, 24, 25, 99, 21]])

In [134]:
arr[3:,3:]

array([[18, 99],
       [99, 21]])

In [136]:
arr[0:,[1,3]]

array([[10, 94],
       [72, 52],
       [52, 94],
       [93, 18],
       [24, 99]])

In [137]:
arr>10

array([[ True, False,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [138]:
arr[arr>10]

array([52, 64, 94, 31, 49, 72, 26, 52, 39, 58, 52, 71, 94, 14, 18, 93, 17,
       18, 99, 58, 24, 25, 99, 21])

In [139]:
arr*arr

array([[2704,  100, 4096, 8836,  961],
       [2401, 5184,  676, 2704, 1521],
       [3364, 2704, 5041, 8836,  196],
       [ 324, 8649,  289,  324, 9801],
       [3364,  576,  625, 9801,  441]])

In [140]:
arr1 = np.random.randint(2,4,(3,3))

In [141]:
arr2 = np.random.randint(2,4,(3,3))

In [142]:
arr1

array([[3, 3, 3],
       [3, 2, 3],
       [3, 2, 2]])

In [143]:
arr2

array([[2, 2, 2],
       [3, 2, 2],
       [2, 3, 2]])

In [144]:
arr1*arr2

array([[6, 6, 6],
       [9, 4, 6],
       [6, 6, 4]])

In [145]:
arr1@arr2

array([[21, 21, 18],
       [18, 19, 16],
       [16, 16, 14]])

In [146]:
arr/0

C:\Users\shiva\AppData\Local\Temp/ipykernel_11240/4291252909.py:1: RuntimeWarning: divide by zero encountered in true_divide
  arr/0


array([[inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf]])

In [147]:
arr**2

array([[2704,  100, 4096, 8836,  961],
       [2401, 5184,  676, 2704, 1521],
       [3364, 2704, 5041, 8836,  196],
       [ 324, 8649,  289,  324, 9801],
       [3364,  576,  625, 9801,  441]], dtype=int32)

In [151]:
arr= np.zeros((3,4))

In [152]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [153]:
a= np.array([1,2,3,4])

In [154]:
a

array([1, 2, 3, 4])

In [155]:
arr+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [156]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [157]:
b= np.array([5,6,7])

In [158]:
b

array([5, 6, 7])

In [161]:
b.reshape(3,1)+arr

array([[5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [162]:
b= np.array([[5,6,7]])

In [163]:
b

array([[5, 6, 7]])

In [164]:
b.T+arr

array([[5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [165]:
arr = np.random.rand(5,4)

In [166]:
arr

array([[0.90659449, 0.38005576, 0.26820247, 0.22362535],
       [0.654855  , 0.39099905, 0.53599895, 0.05133911],
       [0.90459355, 0.31787006, 0.85387403, 0.85367864],
       [0.91363672, 0.63740006, 0.37254491, 0.11934622],
       [0.40631946, 0.32020642, 0.74994662, 0.51529109]])

In [167]:
np.sqrt(arr)

array([[0.95215256, 0.61648663, 0.51788268, 0.47289042],
       [0.80923112, 0.62529917, 0.73211949, 0.22658135],
       [0.95110123, 0.56379966, 0.92405304, 0.92394731],
       [0.95584346, 0.79837339, 0.61036457, 0.34546522],
       [0.63743193, 0.56586785, 0.86599458, 0.71783779]])

In [168]:
np.exp(arr)

array([[2.47587654, 1.46236613, 1.30761187, 1.25060239],
       [1.9248634 , 1.47845711, 1.70915474, 1.0526798 ],
       [2.47092741, 1.37419768, 2.34872829, 2.34826941],
       [2.49337377, 1.89155655, 1.45142366, 1.12675996],
       [1.50128208, 1.37741206, 2.11688701, 1.67412576]])

In [169]:
np.log10(arr)

array([[-0.04258693, -0.42015268, -0.57153722, -0.65047898],
       [-0.18385485, -0.4078243 , -0.27083606, -1.28955169],
       [-0.04354651, -0.49775038, -0.0686062 , -0.06870559],
       [-0.03922645, -0.1955879 , -0.42882137, -0.92319133],
       [-0.39113237, -0.49456997, -0.12496965, -0.28794736]])

In [170]:
arr1 = np.random.randint(2,5, (5,5))

In [171]:
arr1

array([[4, 2, 4, 4, 2],
       [3, 3, 2, 4, 3],
       [4, 3, 4, 4, 4],
       [3, 2, 2, 2, 4],
       [3, 2, 2, 4, 2]])

In [174]:
np.log(arr1)

array([[1.38629436, 0.69314718, 1.38629436, 1.38629436, 0.69314718],
       [1.09861229, 1.09861229, 0.69314718, 1.38629436, 1.09861229],
       [1.38629436, 1.09861229, 1.38629436, 1.38629436, 1.38629436],
       [1.09861229, 0.69314718, 0.69314718, 0.69314718, 1.38629436],
       [1.09861229, 0.69314718, 0.69314718, 1.38629436, 0.69314718]])

In [172]:
np.log10(arr1)

array([[0.60205999, 0.30103   , 0.60205999, 0.60205999, 0.30103   ],
       [0.47712125, 0.47712125, 0.30103   , 0.60205999, 0.47712125],
       [0.60205999, 0.47712125, 0.60205999, 0.60205999, 0.60205999],
       [0.47712125, 0.30103   , 0.30103   , 0.30103   , 0.60205999],
       [0.47712125, 0.30103   , 0.30103   , 0.60205999, 0.30103   ]])

In [173]:
np.log2(arr1)

array([[2.       , 1.       , 2.       , 2.       , 1.       ],
       [1.5849625, 1.5849625, 1.       , 2.       , 1.5849625],
       [2.       , 1.5849625, 2.       , 2.       , 2.       ],
       [1.5849625, 1.       , 1.       , 1.       , 2.       ],
       [1.5849625, 1.       , 1.       , 2.       , 1.       ]])

In [175]:
np.random.seed(13)

In [183]:
np.random.seed(13)
np.random.rand(2,4)

array([[0.77770241, 0.23754122, 0.82427853, 0.9657492 ],
       [0.97260111, 0.45344925, 0.60904246, 0.77552651]])